spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pierre_play
    username: pierre
    password: amXU-d/Och!Mo9pC
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api/docs